title: Kishor Website
author: Kishor Pulagam
email: pulagamnkr@gmail.ocm
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This website tells the details about me and shows the works done by me.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  npulagam # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
